
export const FETCH_CONFIG = "FETCH_CONFIG";
export const FETCH_CONFIG_SUCCESS = "FETCH_CONFIG_SUCCESS";
export const FETCH_CONFIG_FAILED = "FETCH_CONFIG_FAILED";
export const SET_QUERY_PARAMS = "SET_QUERY_PARAMS";
export const FETCH_CONTENT = "FETCH_CONTENT";
export const FETCH_CONTENT_SUCCESS = "FETCH_CONTENT_SUCCESS";
export const FETCH_CONTENT_FAILED = "FETCH_CONTENT_FAILED";
export const FETCH_ACCOUNTS = "FETCH_ACCOUNTS";
export const FETCH_ACCOUNTS_SUCCESS = "FETCH_ACCOUNTS_SUCCESS";
export const FETCH_ACCOUNTS_FAILED = "FETCH_ACCOUNTS_FAILED";
export const FETCH_ACCOUNTS_DETAILS = "FETCH_ACCOUNTS_DETAILS";
export const FETCH_ACCOUNTS_DETAILS_SUCCESS = "FETCH_ACCOUNTS_DETAILS_SUCCESS";
export const FETCH_ACCOUNTS_DETAILS_FAILED = "FETCH_ACCOUNTS_DETAILS_FAILED";
//redirect
export const REDIRECT_SAMPLE2 = "REDIRECT_SAMPLE2";